version: '3.8'

services:
  api:
    build: .
    container_name: shipment-tracker-api
    restart: always
    ports:
      - "8899:8899"
    env_file:
      - .env
    networks:
      - shipment-network

networks:
  shipment-network:
    driver: bridge
